### PR TITLE
Emoticons popup

### PR DESCRIPTION
**Pull request by StrongEdward**

### CODE REVIEW

**Comment by Kev** [comment]
Thanks. Can you squash this into a single commit so I can put it into our review/CI system, please?

**Comment by StrongEdward** [comment]
Done.

2015-03-23 20:27 GMT+01:00 Kevin Smith <notifications@github.com>:

**Comment by Kev** [comment]
Thanks. This passes CI. Could you make a couple of tweaks (above), please. Could you also switch to using your name for the committer in Git, please? Makes life easier for us.

**Comment by StrongEdward** [comment]
I answered for your comments and send a commit with fixes. Please tell me
when you checked it so I will squash these commits.

2015-03-24 8:47 GMT+01:00 Kevin Smith <notifications@github.com>:

**Comment by Kev** [comment]
Those changes look good, thanks. Could you please squash them together, along with not using the typedef in the ctor parameters (keeping the same Change-Id so our CI/Review system knows it's a new version of the same patch), and I'll feed it back into the sausage machine.

**Comment by Kev** [comment]
Putting the typedef in the cpp would be preferable for me, but having it in the private bit header and not used in the API would be ok. Do you want a review of the patch as submitted above?

**Comment by StrongEdward** [comment]
Yes, tell me what you think about the code, please.

**Comment by Kev** [comment]
Thanks. I'll merge this now.

**Pull request closed without merging**
