### PR TITLE
Update namespace for MIX Elements

### PR DESCRIPTION
**Pull request by tarun018**

### CODE REVIEW

**Comment by tfar** [comment]
Please rebase on current master.

**Comment by tarun018** [comment]
Rebased.

**Comment by tarun018** [comment]
Updated commit message.

**Comment by tarun018** [comment]
I'll update this PR to include update to all elements parsers and serializers.

**Comment by tfar** [comment]
Alright. So should we get the other parser PRs merged first?

**Comment by tarun018** [comment]
We can merge till MIXLeave. I'll set up this PR for MIXCreate, MIXDestroy, MIXJoin, MIXParticipant, MIXSubscribe and MIXUserPreference. For other unmerged elements, I'll directly update their respective PRs.

**Comment by tfar** [comment]
Alright. MIXLeave stuff has already been merged.

**Comment by tarun018** [comment]
Updated namespaces for merged elements.

**Comment by tfar** [comment]
Thank you for this contribution. It has been submitted and merged upstream.

**Pull request closed without merging**
